[package]
name = "oscilloscope"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
image = "0.24.6"
itertools = "0.10.3"
rand = "0.8.5"
rand_chacha = "0.3.1"
libxm = "1.0.0"